### PR TITLE
F0.5, F2 and Accuracy for daicx

### PR DESCRIPTION
**Pull request by Far0n**
C++ implementation of optimizing F0.5, F2 and Accuracy with python bindings.

### CODE REVIEW

**Comment by mdymczyk** [comment]
@Far0n looks good! Could we get some Python unit tests?

**Comment by pseudotensor** [comment]
Yes, unit tests would be good.  Let's do that as a next pass since this is for fixing a critical DAI issue.

**Comment by Far0n** [comment]
@mdymczyk you mean directly in h2o4gpu? currently the tests are in DAI, because the code is only used there.

**Comment by mdymczyk** [comment]
@Far0n yes if we could have some tests here it would be great, having tests in DAI is better than nothing but might be a bit too late to find potential issues ;-)

**Comment by Far0n** [comment]
@mdymczyk that's true. :) I will deliver in addition.

**Pull request merged**
