### PR TITLE
Revert xgboost until invalid device original fixed by Jiaming et al.

### PR DESCRIPTION
**Pull request by pseudotensor**

### CODE REVIEW

**Comment by trivialfis** [comment]
Hi, can you be more specific? I can make a PR for fixing right now.  But I haven't seen any issues mentioned me yet.  Sorry.

**Comment by trivialfis** [comment]
@pseudotensor , Hi, would https://github.com/dmlc/xgboost/pull/3693 help?

**Comment by pseudotensor** [comment]
I didn't hear anything back from @trivialfis for 14 hours, so I'm going to merge this and use it.

**Comment by trivialfis** [comment]
Hi @pseudotensor , PR https://github.com/dmlc/xgboost/pull/3693 should fix the issue, but currently I don't have the resource to test it under multi-gpu (that's probably why the bug is introduced in the first place).  I will get to it once I can test it.  Sorry for the mess.

**Pull request merged**
