### PR TITLE
Cpu monika

### PR DESCRIPTION
**Pull request by stjoern**
CPU build

### CODE REVIEW

**Comment by pseudotensor** [comment]
I updated the xgboost module and added stuff in the Makefile to build the xgboost locally with cpu support instead of pulling from jenkins the nccl-cuda9.  This way we can work on h2o4gpu for now and not worry about xgboost jenkins.

**Comment by pseudotensor** [comment]
and I ran "make Jenkinsfiles" to update your Jenkins files.

**Comment by pseudotensor** [comment]
But it's not clear what is going on with jenkins.  It errors out but I don't see error.

**Comment by pseudotensor** [comment]
It looks like the problem is after the dockerfile is built but the make process never happened.  So issue is once in: scripts/make-docker-devel.sh .  I added a fullinstalljenkins-cpu to use.

**Comment by pseudotensor** [comment]
So locally (and should be on jenkins now) the issue is still with avoiding gpu stuff for the cpu build.  See below for the first error hit.  Just needs more isolation/control to avoid gpu building for cpu build.

```
Makefile:285: recipe for target 'build/gpu/projector/projector_direct_dense.o' failed
make: [build/gpu/projector/projector_direct_dense.o] Error 127 (ignored)
std=c++11 -O3 -D_GITHASH_=\"6de87ea\" -Xcompiler -fPIC -Xcompiler -fopenmp -I/usr/share/R/include -DUSEICC=0 -DUSEMKL=0 -I/usr/include/openblas build/gpu/tsvd/tsvd.o build/gpu/pca/pca.o build/gpu/data/matrix.o build/gpu/kmeans/kmeans_h2o4gpu.o build/gpu/kmeans/kmeans_labels.o build/gpu/h2o4gpuglm.o build/gpu/warmstart.o build/gpu/utils.o build/gpu/p2pbwcheck.o build/gpu/bwcheck.o build/gpu/elastic_net_ptr.o build/common/logger.o build/common/utils.o build/gpu/matrix/matrix_dense.o build/gpu/matrix/matrix_sparse.o build/gpu/projector/projector_cgls.o build/gpu/projector/projector_direct_dense.o -dlink -o build/gpu/h2o4gpu_link.o
/bin/bash: -O3: command not found
Makefile:267: recipe for target 'build/gpu/h2o4gpu_link.o' failed
make: [build/gpu/h2o4gpu_link.o] Error 127 (ignored)
mkdir -p build/cpu/projector
touch gpulib
ar cr build/gpu/h2o4gpu.a build/gpu/h2o4gpu_link.o build/gpu/tsvd/tsvd.o build/gpu/pca/pca.o build/gpu/data/matrix.o build/gpu/kmeans/kmeans_h2o4gpu.o build/gpu/kmeans/kmeans_labels.o build/gpu/h2o4gpuglm.o build/gpu/warmstart.o build/gpu/utils.o build/gpu/p2pbwcheck.o build/gpu/bwcheck.o build/gpu/elastic_net_ptr.o build/common/logger.o build/common/utils.o build/gpu/matrix/matrix_dense.o build/gpu/matrix/matrix_sparse.o build/gpu/projector/projector_cgls.o build/gpu/projector/projector_direct_dense.o build/cpu/projector/projector_cgls.o build/cpu/projector/projector_direct_dense.o
ar: build/gpu/h2o4gpu_link.o: No such file or directory
Makefile:199: recipe for target 'gpulib' failed
make: *** [gpulib] Error 1
jon@mr-dl10:~/h2o4gpu/src$ 

```

**Comment by pseudotensor** [comment]
Yes, Jenkins reaches same point as my local build:

http://mr-0xc1:8080/blue/organizations/jenkins/h2o4gpu-nccl-cuda8/detail/PR-427/7/pipeline/
```

cpu/matrix/matrix_dense.cpp:617:10: warning: format '%d' expects argument of type 'int', but argument 5 has type 'size_t {aka long unsigned int}' [-Wformat=]

/bin/bash: -O3: command not found

ar: build/gpu/h2o4gpu_link.o: No such file or directory

Makefile:199: recipe for target 'gpulib' failed

make[1]: *** [gpulib] Error 1

make[1]: *** Waiting for unfinished jobs....

make: *** [cpp] Error 2

Makefile:120: recipe for target 'cpp' failed

script returned exit code 2
```

**Comment by mdymczyk** [comment]
This is great @stjoern ! And huge thanks @pseudotensor for reviewing it :-) Can we get an update to the readme (DEVEL.md) explaining how to build CPU and how to build the GPU versions? Thanks!

**Pull request merged**
