### PR TITLE
Support supervised models and added XGBoost random_forest_classifier

### PR DESCRIPTION
**Pull request by terrytangyuan**
* Support supervised models
* Added XGBoost random_forest_classifier
* Allowed `numeric` model input

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@navdeep-G This is ready for review. Though I will need to update a few minor things once the utility functions I added in https://github.com/h2oai/h2o4gpu/pull/370 are merged.

**Comment by navdeep-G** [comment]
I will wait for #370 to be merged before full review.

**Comment by pseudotensor** [comment]
@navdeep-G can review soon now that #370 merged?

**Comment by navdeep-G** [comment]
LGTM. This can be merged and then you can merge #380 after addressing my comments.

**Pull request merged**
