### PR TITLE
Probably Fixes #712

### LINKED ISSUE #712: excess messages from xgboost -- s3 vs. local build issue
Consider a file simple.py:
```
import numpy as np
import pandas as pd
X = pd.DataFrame(np.array([[1,2,3],[4,5,6]]), columns=['A', 'B', 'C'])
y = np.array([1.5,2.3])
from xgboost import XGBRegressor
model = XGBRegressor(
    booster='gblinear',
    objective='reg:linear', alpha_reg=0.5, lambda_reg=0.5)
print("before model fit")
model.fit(X, y)
print("after model fit")
print("model.predict(X)")
preds=model.predict(X)
print(preds)
```

Due to https://github.com/dmlc/xgboost/issues/3953 I fixed this in xgboost h2oai branch, but despite this the build on s3 from correct hash sill has the same problem, as if s3 isn't really the correct build.
```
wget http://h2o-release.s3.amazonaws.com/h2o4gpu/snapshots/ai/h2o/h2o4gpu/0.3-cuda9/h2o4gpu-0.3.0.10000%2Bmaster.4cb6914-cp36-cp36m-linux_x86_64.whl
pip install h2o4gpu-0.3.0.10000%2Bmaster.4cb6914-cp36-cp36m-linux_x86_64.whl
```
leads to:
```
jon@pseudotensor:~/h2oai$ CUDA_VISIBLE_DEVICES= python simple.py 
before model fit
[21:02:05] /root/repo/xgboost/rabit/include/rabit/./internal/../../dmlc/./logging.h:300: [21:02:05] /root/repo/xgboost/src/common/./common.h:41: /root/repo/xgboost/src/common/common.cu: 13: no CUDA-capable device is detected

Stack trace returned 10 entries:
[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x26) [0x7f20b36cec16]
[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN2dh16ThrowOnCudaErrorE9cudaErrorPKci+0x15b) [0x7f20b389772b]
[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost14AllVisibleImpl10AllVisibleEv+0x29) [0x7f20b394f569]
[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost6GPUSet3AllEiii+0x32) [0x7f20b38be8e2]
[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3obj10RegLossObjINS0_16LinearSquareLossEE9ConfigureERKSt6vectorISt4pairISsSsESaIS6_EE+0x233) [0x7f20b38f0a33]
[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11ObjFunction9ConfigureISt17_Rb_tree_iteratorISt4pairIKSsSsEEEEvT_S7_+0xd1) [0x7f20b3752091]
[bt] (6) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11LearnerImpl13LazyInitModelEv+0x3bf) [0x7f20b375a1df]
[bt] (7) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x52) [0x7f20b36dd3b2]
[bt] (8) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f2106114356]
[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call+0x3f1) [0x7f21061130b1]

[21:02:05] /root/repo/xgboost/rabit/include/rabit/./internal/../../dmlc/./logging.h:300: [21:02:05] /root/repo/xgboost/src/common/./common.h:41: /root/repo/xgboost/src/common/./device_helpers.cuh: 1026: no CUDA-capable device is detected

Stack trace returned 10 entries:
[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x26) [0x7f20b36cec16]
[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN2dh16ThrowOnCudaErrorE9cudaErrorPKci+0x15b) [0x7f20b389772b]
[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN2dh18ExecuteIndexShardsIN7xgboost20HostDeviceVectorImplImE11DeviceShardEZNS3_C1ERKS3_EUliRS4_E_EEvPSt6vectorIT_SaISA_EET0_+0x47) [0x7f20b38a55a7]
[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost16HostDeviceVectorImEC1ERKS1_+0x1d5) [0x7f20b38b29b5]
[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost4data13SimpleDMatrix16GetColumnBatchesEv+0xe6) [0x7f20b370f796]
[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost6linear14ShotgunUpdater6UpdateEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixEPNS_3gbm13GBLinearModelEd+0x27a) [0x7f20b376ba9a]
[bt] (6) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm8GBLinear7DoBoostEPNS_7DMatrixEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_11ObjFunctionE+0x47c) [0x7f20b3733fbc]
[bt] (7) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x400) [0x7f20b3759940]
[bt] (8) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x35) [0x7f20b36dd395]
[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f2106114356]

[21:02:05] /root/repo/xgboost/rabit/include/rabit/./internal/../../dmlc/./logging.h:300: [21:02:05] /root/repo/xgboost/src/common/./common.h:41: /root/repo/xgboost/src/common/./device_helpers.cuh: 1026: no CUDA-capable device is detected

Stack trace returned 10 entries:
[bt] (0) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN4dmlc15LogMessageFatalD2Ev+0x26) [0x7f20b36cec16]
[bt] (1) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN2dh16ThrowOnCudaErrorE9cudaErrorPKci+0x15b) [0x7f20b389772b]
[bt] (2) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN2dh18ExecuteIndexShardsIN7xgboost20HostDeviceVectorImplINS1_5EntryEE11DeviceShardEZNS4_C1ERKS4_EUliRS5_E_EEvPSt6vectorIT_SaISB_EET0_+0x47) [0x7f20b38a7a17]
[bt] (3) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost16HostDeviceVectorINS_5EntryEEC1ERKS2_+0x1d5) [0x7f20b38b5b25]
[bt] (4) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost4data13SimpleDMatrix16GetColumnBatchesEv+0xf6) [0x7f20b370f7a6]
[bt] (5) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost6linear14ShotgunUpdater6UpdateEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_7DMatrixEPNS_3gbm13GBLinearModelEd+0x27a) [0x7f20b376ba9a]
[bt] (6) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost3gbm8GBLinear7DoBoostEPNS_7DMatrixEPNS_16HostDeviceVectorINS_6detail20GradientPairInternalIfEEEEPNS_11ObjFunctionE+0x47c) [0x7f20b3733fbc]
[bt] (7) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(_ZN7xgboost11LearnerImpl13UpdateOneIterEiPNS_7DMatrixE+0x400) [0x7f20b3759940]
[bt] (8) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x35) [0x7f20b36dd395]
[bt] (9) /home/jon/.pyenv/versions/3.6.4/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f2106114356]

after model fit
model.predict(X)
[1.5358431 2.255315 ]
jon@pseudotensor:~/h2oai$ 

```

I checked all hashes in h2o4gpu, xgboost, and all seems ok.  I don't understand.

If I install from xgboost directly:
```
git clone https://github.com/h2oai/xgboost
cd xgboost
git checkout h2oai
make -f Makefile2
pip install python-package/dist/xgboost*.whl
```
gives no excess messages. i.e.

```
jon@pseudotensor:~/h2o4gpu$ CUDA_VISIBLE_DEVICES= python simple.py 
before model fit
after model fit
model.predict(X)
[1.5358431 2.255315 ]
jon@pseudotensor:~/h2o4gpu$ 
```

If I build h2o4gpu using "make fullinstall" locally, I have no excess messages using a fresh env.

### PR DESCRIPTION
**Pull request by pseudotensor**

### CODE REVIEW

**Comment by pseudotensor** [comment]
low risk of issue, no typos, so will merge.

**Comment by sh1ng** [comment]
Don't we need to check `cudaError_t` status?

**Comment by pseudotensor** [comment]
Ah, you mean it won't throw exception unless we force it?

**Comment by pseudotensor** [comment]
```
#define safe_cuda(ans) ThrowOnCudaError((ans), __FILE__, __LINE__)

inline cudaError_t ThrowOnCudaError(cudaError_t code, const char *file,
                                    int line) {
  if (code != cudaSuccess) {
    LOG(FATAL) << thrust::system_error(code, thrust::cuda_category(),
                                       std::string{file} + ": " +  // NOLINT
                                       std::to_string(line)).what();
  }
  return code;
}
```

This logs a fatal exception because the cudaError_t was not successful.  However, if CUDA_VISIBLE_DEVICES= is set, then literally the cuda call itself will fail and no error code is returned.

**Comment by pseudotensor** [comment]
```
jon@pseudotensor:~/xgboost.h2oai$ python simple.py 
before model fit
after model fit
model.predict(X)
[1.5358431 2.255315 ]
jon@pseudotensor:~/xgboost.h2oai$ CUDA_VISIBLE_DEVICES= python simple.py 
before model fit
after model fit
model.predict(X)
[1.5358431 2.255315 ]
jon@pseudotensor:~/xgboost.h2oai$ 
```

Seemed to work fine, but I guess you are worried that it's somehow still setting (or not setting) the number of visible gpus?

**Comment by pseudotensor** [comment]
But note that the default is `int n_visgpus = 0;`  So when the cuda call `cudaGetDeviceCount(&n_visgpus);` fails, it'll not set n_visgpus and it'll be the default of zero.

**Pull request merged**
