### PR TITLE
Reproduce hang import

### PR DESCRIPTION
**Pull request by sh1ng**

### CODE REVIEW

**Comment by sh1ng** [comment]
It hangs from time to time on PRs.
stack trace from #716 

```
(gdb) bt
#0  0x00007f1dfe612d47 in sched_yield () from target:/usr/lib64/libc.so.6
#1  0x00007f1d0b0fede5 in ncclCpuBarrierWait (comm=comm@entry=0x563036e90de0)
    at misc/enqueue.cu:146
#2  0x00007f1d0b0ffbb2 in ncclEnqueueCheck (
    func=func@entry=0x7f1d0b117510 <ncclAllReduceFunc(void const*, void*, unsigned long, ncclDataType_t, ncclRedOp_t, int, ncclComm*, CUstream_st*)>, 
    primName=primName@entry=0x7f1d0b14c8a1 "AllReduce", sendbuff=0x7f1cc1a17800, 
    recvbuff=0x7f1cc1a17800, count=6890, type=ncclFloat64, op=ncclSum, root=root@entry=0, 
    comm=0x563036e90de0, stream=stream@entry=0x563037008dd0) at misc/enqueue.cu:205
#3  0x00007f1d0b117c3e in ncclAllReduce (sendbuff=<optimized out>, recvbuff=<optimized out>, 
    count=<optimized out>, datatype=<optimized out>, op=<optimized out>, comm=<optimized out>, 
    stream=0x563037008dd0) at collectives/all_reduce.cu:29
#4  0x00007f1d0b03f5d6 in dh::AllReducer::AllReduceSum (count=6890, recvbuff=0x7f1cc1a17800, 
    sendbuff=0x7f1cc1a17800, communication_group_idx=0, this=<optimized out>)
    at /root/repo/xgboost/src/tree/../common/device_helpers.cuh:941
#5  xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::AllReduceHist(int)::{lambda(int, std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >&)#1}::operator()(int, std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >&) const (idx=0, shard=..., __closure=<optimized out>)
    at /root/repo/xgboost/src/tree/updater_gpu_hist.cu:1043
#6  dh::ExecuteIndexShards<std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >, xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::AllReduceHist(int)::{lambda(int, std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >&)#1}>(std::vector<std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >, std::allocator<std::vector> >*, xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::AllReduceHist(int)::{lambda(int, std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >&)#1})::{lambda()#1}::operator() () at /root/repo/xgboost/src/tree/../common/device_helpers.cuh:1055
#7  0x00007f1d0b04d674 in dh::ExecuteIndexShards<std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >, xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::AllReduceHist(int)::{lambda(int, std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >&)#1}>(std::vector<std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::t--Type <RET> for more, q to quit, c to continue without paging--
ree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >, std::allocator<std::vector> >*, xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::AllReduceHist(int)::{lambda(int, std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >&)#1})::{lambda()#1}::operator()() const (__closure=0x7ffc7bc5eee0)
    at /root/repo/xgboost/src/tree/../common/device_helpers.cuh:1053
#8  dh::SaveCudaContext::SaveCudaContext<dh::ExecuteIndexShards(std::vector<T>*, FunctionT) [with T = std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >; FunctionT = xgboost::tree::GPUHistMakerSpecialised<GradientSumT>::AllReduceHist(int) [with GradientSumT = xgboost::detail::GradientPairInternal<double>]::__lambda9]::__lambda2> (func=..., 
    this=0x7ffc7bc5eed0) at /root/repo/xgboost/src/tree/../common/device_helpers.cuh:1030
#9  dh::ExecuteIndexShards<std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >, xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::AllReduceHist(int)::{lambda(int, std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >&)#1}>(std::vector<std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >, std::allocator<std::vector> >*, xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::AllReduceHist(int)::{lambda(int, std::unique_ptr<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >, std::default_delete<xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> > > >&)#1}) (shards=shards@entry=0x563036eaa880, f=...)
    at /root/repo/xgboost/src/tree/../common/device_helpers.cuh:1052
#10 0x00007f1d0b04d763 in xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::AllReduceHist (this=this@entry=0x563036eaa6d0, nidx=nidx@entry=0)
    at /root/repo/xgboost/src/tree/updater_gpu_hist.cu:1039
#11 0x00007f1d0b05e9b6 in xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::InitRoot (this=this@entry=0x563036eaa6d0, p_tree=p_tree@entry=0x563036eaae30)
    at /root/repo/xgboost/src/tree/updater_gpu_hist.cu:1138
#12 0x00007f1d0b06477f in xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::UpdateTree (this=this@entry=0x563036eaa6d0, gpair=gpair@entry=0x563034b5ea78, 
    p_fmat=p_fmat@entry=0x563031d2bdd0, p_tree=0x563036eaae30)
    at /root/repo/xgboost/src/tree/updater_gpu_hist.cu:1230
#13 0x00007f1d0b065ce2 in xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::Update (this=0x563036eaa6d0, gpair=0x563034b5ea78, dmat=0x563031d2bdd0, trees=...)
    at /root/repo/xgboost/src/tree/updater_gpu_hist.cu:955
#14 0x00007f1d0ae61517 in xgboost::gbm::GBTree::BoostNewTrees (this=this@entry=0x563034bbcff0, 
    gpair=gpair@entry=0x563034b5ea78, p_fmat=p_fmat@entry=0x563031d2bdd0, 
    bst_group=bst_group@entry=0, ret=ret@entry=0x7ffc7bc5f900)
--Type <RET> for more, q to quit, c to continue without paging--
    at /root/repo/xgboost/src/gbm/gbtree.cc:293
#15 0x00007f1d0ae627d5 in xgboost::gbm::GBTree::DoBoost (this=0x563034bbcff0, 
    p_fmat=0x563031d2bdd0, in_gpair=0x563034b5ea78, obj=<optimized out>)
    at /root/repo/xgboost/src/gbm/gbtree.cc:180
#16 0x00007f1d0ae71030 in xgboost::LearnerImpl::UpdateOneIter (this=0x563034b5e920, iter=0, 
    train=0x563031d2bdd0) at /root/repo/xgboost/src/learner.cc:503
#17 0x00007f1d0adf4a85 in XGBoosterUpdateOneIter (handle=0x563030f8b720, iter=0, 
    dtrain=0x563031b6d1f0) at /root/repo/xgboost/src/c_api/c_api.cc:905
#18 0x00007f1df73a7ec0 in ffi_call_unix64 ()
   from target:/opt/h2oai/h2o4gpu/python/lib/python3.6/lib-dynload/../../libffi.so.6
#19 0x00007f1df73a787d in ffi_call ()
   from target:/opt/h2oai/h2o4gpu/python/lib/python3.6/lib-dynload/../../libffi.so.6
#20 0x00007f1df75bcdee in _ctypes_callproc ()
   from target:/opt/h2oai/h2o4gpu/python/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so
#21 0x00007f1df75bd825 in PyCFuncPtr_call ()
   from target:/opt/h2oai/h2o4gpu/python/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so

```

**Comment by pseudotensor** [comment]
Ya, looks like a very different kind of hang than seen on DAI.

**Comment by sh1ng** [comment]
```
Thread 6 (LWP 23069):
#0  futex_wait (val=289096, addr=0x56357951dbb4)
    at /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/work/.build/src/gcc-7.2.0/libgomp/config/linux/x86/futex.h:44
#1  do_wait (addr=addr@entry=0x56357951dbb4, val=val@entry=289096)
    at /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/work/.build/src/gcc-7.2.0/libgomp/config/linux/wait.h:67
#2  0x00007f781d37f7ab in gomp_barrier_wait_end (bar=0x56357951dbb0, state=289096)
    at /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/work/.build/src/gcc-7.2.0/libgomp/config/linux/bar.c:48
#3  0x00007f781d37db27 in gomp_simple_barrier_wait (bar=<optimized out>)
    at /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/work/.build/src/gcc-7.2.0/libgomp/config/posix/simple-bar.h:60
#4  gomp_thread_start (xdata=<optimized out>)
    at /home/msarahan/miniconda2/conda-bld/compilers_linux-64_1507259624353/work/.build/src/gcc-7.2.0/lib--Type <RET> for more, q to quit, c to continue without paging--
gomp/team.c:124
#5  0x00007f790b626dd5 in start_thread () from target:/usr/lib64/libpthread.so.0
#6  0x00007f790b34fead in clone () from target:/usr/lib64/libc.so.6

Thread 5 (LWP 23019):
#0  0x00007f790b62a965 in pthread_cond_wait@@GLIBC_2.3.2 () from target:/usr/lib64/libpthread.so.0
#1  0x00007f77f896a8ad in ?? () from target:/usr/lib64/libcuda.so.1
#2  0x00007f77f8913545 in ?? () from target:/usr/lib64/libcuda.so.1
#3  0x00007f77f8969ae8 in ?? () from target:/usr/lib64/libcuda.so.1
#4  0x00007f790b626dd5 in start_thread () from target:/usr/lib64/libpthread.so.0
#5  0x00007f790b34fead in clone () from target:/usr/lib64/libc.so.6

Thread 4 (LWP 22963):
#0  0x00007f790b34520d in poll () from target:/usr/lib64/libc.so.6
#1  0x00007f77f8967503 in ?? () from target:/usr/lib64/libcuda.so.1
#2  0x00007f77f89c9b6d in ?? () from target:/usr/lib64/libcuda.so.1
#3  0x00007f77f8969ae8 in ?? () from target:/usr/lib64/libcuda.so.1
#4  0x00007f790b626dd5 in start_thread () from target:/usr/lib64/libpthread.so.0
#5  0x00007f790b34fead in clone () from target:/usr/lib64/libc.so.6

Thread 3 (LWP 22962):
#0  0x00007f790b35133f in accept4 () from target:/usr/lib64/libc.so.6
#1  0x00007f77f89684aa in ?? () from target:/usr/lib64/libcuda.so.1
#2  0x00007f77f895ac0d in ?? () from target:/usr/lib64/libcuda.so.1
#3  0x00007f77f8969ae8 in ?? () from target:/usr/lib64/libcuda.so.1
#4  0x00007f790b626dd5 in start_thread () from target:/usr/lib64/libpthread.so.0
#5  0x00007f790b34fead in clone () from target:/usr/lib64/libc.so.6

Thread 2 (LWP 22351):
#0  0x00007f790b62d6fd in read () from target:/usr/lib64/libpthread.so.0
#1  0x0000563575e91597 in _Py_read ()
#2  0x0000563575e91737 in _io_FileIO_readinto ()
#3  0x0000563575e4ff95 in _PyCFunction_FastCallDict ()
#4  0x0000563575e503ef in _PyObject_FastCallDict ()
#5  0x0000563575eb341c in PyObject_CallMethodObjArgs ()
#6  0x0000563575ed21c6 in _bufferedreader_raw_read ()
#7  0x0000563575ed24ab in _bufferedreader_fill_buffer ()
#8  0x0000563575ee2567 in _io__Buffered_read ()
#9  0x0000563575e4ff11 in _PyCFunction_FastCallDict ()
#10 0x0000563575eddbec in call_function ()
#11 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
--Type <RET> for more, q to quit, c to continue without paging--
#12 0x0000563575ed77db in fast_function ()
#13 0x0000563575eddcc5 in call_function ()
#14 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#15 0x0000563575ed77db in fast_function ()
#16 0x0000563575eddcc5 in call_function ()
#17 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#18 0x0000563575ed6dfe in _PyEval_EvalCodeWithName ()
#19 0x0000563575ed8108 in _PyFunction_FastCallDict ()
#20 0x0000563575e5039f in _PyObject_FastCallDict ()
#21 0x0000563575e54ff3 in _PyObject_Call_Prepend ()
#22 0x0000563575e4fdde in PyObject_Call ()
#23 0x0000563575f03994 in _PyEval_EvalFrameDefault ()
#24 0x0000563575ed77db in fast_function ()
#25 0x0000563575eddcc5 in call_function ()
#26 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#27 0x0000563575ed7e4b in _PyFunction_FastCallDict ()
#28 0x0000563575e5039f in _PyObject_FastCallDict ()
#29 0x0000563575e54ff3 in _PyObject_Call_Prepend ()
#30 0x0000563575e4fdde in PyObject_Call ()
#31 0x0000563575f4f426 in t_bootstrap ()
#32 0x00007f790b626dd5 in start_thread () from target:/usr/lib64/libpthread.so.0
#33 0x00007f790b34fead in clone () from target:/usr/lib64/libc.so.6

Thread 1 (LWP 22349):
#0  0x00007f790b62cadb in do_futex_wait.constprop () from target:/usr/lib64/libpthread.so.0
#1  0x00007f790b62cb6f in __new_sem_wait_slow.constprop.0 () from target:/usr/lib64/libpthread.so.0
#2  0x00007f790b62cc0b in sem_wait@@GLIBC_2.2.5 () from target:/usr/lib64/libpthread.so.0
#3  0x0000563575e2a516 in PyThread_acquire_lock_timed ()
#4  0x0000563575ebeafc in lock_PyThread_acquire_lock ()
#5  0x0000563575e4ffd4 in _PyCFunction_FastCallDict ()
#6  0x0000563575eddbec in call_function ()
#7  0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#8  0x0000563575ed69a6 in _PyEval_EvalCodeWithName ()
#9  0x0000563575ed7a11 in fast_function ()
#10 0x0000563575eddcc5 in call_function ()
#11 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#12 0x0000563575ed69a6 in _PyEval_EvalCodeWithName ()
#13 0x0000563575ed7a11 in fast_function ()
#14 0x0000563575eddcc5 in call_function ()
#15 0x0000563575f02eb1 in _PyEval_EvalFrameDefault ()
#16 0x0000563575ed69a6 in _PyEval_EvalCodeWithName ()
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x0000563575ed7a11 in fast_function ()
#18 0x0000563575eddcc5 in call_function ()
#19 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#20 0x0000563575ed7e4b in _PyFunction_FastCallDict ()
#21 0x0000563575e5039f in _PyObject_FastCallDict ()
#22 0x0000563575e54ff3 in _PyObject_Call_Prepend ()
#23 0x0000563575e4fdde in PyObject_Call ()
#24 0x0000563575f03994 in _PyEval_EvalFrameDefault ()
#25 0x0000563575ed6dfe in _PyEval_EvalCodeWithName ()
#26 0x0000563575ed7a11 in fast_function ()
#27 0x0000563575eddcc5 in call_function ()
#28 0x0000563575f02eb1 in _PyEval_EvalFrameDefault ()
#29 0x0000563575ed69a6 in _PyEval_EvalCodeWithName ()
#30 0x0000563575ed7a11 in fast_function ()
#31 0x0000563575eddcc5 in call_function ()
#32 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#33 0x0000563575ed77db in fast_function ()
#34 0x0000563575eddcc5 in call_function ()
#35 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#36 0x0000563575ed69a6 in _PyEval_EvalCodeWithName ()
#37 0x0000563575ed8108 in _PyFunction_FastCallDict ()
#38 0x0000563575e5039f in _PyObject_FastCallDict ()
#39 0x0000563575e54ff3 in _PyObject_Call_Prepend ()
#40 0x0000563575e4fdde in PyObject_Call ()
#41 0x0000563575eab901 in slot_tp_call ()
#42 0x0000563575e501bb in _PyObject_FastCallDict ()
#43 0x0000563575ed7cfa in _PyObject_FastCallKeywords ()
#44 0x0000563575eddd3e in call_function ()
#45 0x0000563575f02eb1 in _PyEval_EvalFrameDefault ()
#46 0x0000563575ed77db in fast_function ()
#47 0x0000563575eddcc5 in call_function ()
#48 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#49 0x0000563575ed77db in fast_function ()
#50 0x0000563575eddcc5 in call_function ()
#51 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#52 0x0000563575ed8529 in PyEval_EvalCodeEx ()
#53 0x0000563575ed9344 in function_call ()
#54 0x0000563575e4fdde in PyObject_Call ()
#55 0x0000563575f03994 in _PyEval_EvalFrameDefault ()
#56 0x0000563575ed6dfe in _PyEval_EvalCodeWithName ()
#57 0x0000563575ed7a11 in fast_function ()
--Type <RET> for more, q to quit, c to continue without paging--
#58 0x0000563575eddcc5 in call_function ()
#59 0x0000563575f02eb1 in _PyEval_EvalFrameDefault ()
#60 0x0000563575ed69a6 in _PyEval_EvalCodeWithName ()
#61 0x0000563575ed7a11 in fast_function ()
#62 0x0000563575eddcc5 in call_function ()
#63 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#64 0x0000563575ed77db in fast_function ()
#65 0x0000563575eddcc5 in call_function ()
#66 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#67 0x0000563575ed69a6 in _PyEval_EvalCodeWithName ()
#68 0x0000563575ed8108 in _PyFunction_FastCallDict ()
#69 0x0000563575e5039f in _PyObject_FastCallDict ()
#70 0x0000563575e54ff3 in _PyObject_Call_Prepend ()
#71 0x0000563575e4fdde in PyObject_Call ()
#72 0x0000563575eab901 in slot_tp_call ()
#73 0x0000563575e501bb in _PyObject_FastCallDict ()
#74 0x0000563575ed7cfa in _PyObject_FastCallKeywords ()
#75 0x0000563575eddd3e in call_function ()
#76 0x0000563575f02eb1 in _PyEval_EvalFrameDefault ()
#77 0x0000563575ed8529 in PyEval_EvalCodeEx ()
#78 0x0000563575ed92cc in PyEval_EvalCode ()
#79 0x0000563575effa8d in builtin_exec ()
#80 0x0000563575e4ff11 in _PyCFunction_FastCallDict ()
#81 0x0000563575eddbec in call_function ()
#82 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#83 0x0000563575ed77db in fast_function ()
#84 0x0000563575eddcc5 in call_function ()
#85 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#86 0x0000563575ed7e4b in _PyFunction_FastCallDict ()
#87 0x0000563575e5039f in _PyObject_FastCallDict ()
#88 0x0000563575e54ff3 in _PyObject_Call_Prepend ()
#89 0x0000563575e4fdde in PyObject_Call ()
#90 0x0000563575f03994 in _PyEval_EvalFrameDefault ()
#91 0x0000563575ed77db in fast_function ()
#92 0x0000563575eddcc5 in call_function ()
#93 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#94 0x0000563575ed77db in fast_function ()
#95 0x0000563575eddcc5 in call_function ()
#96 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#97 0x0000563575ed77db in fast_function ()
#98 0x0000563575eddcc5 in call_function ()
--Type <RET> for more, q to quit, c to continue without paging--
#99 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#100 0x0000563575ed6dfe in _PyEval_EvalCodeWithName ()
#101 0x0000563575ed7a11 in fast_function ()
#102 0x0000563575eddcc5 in call_function ()
#103 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#104 0x0000563575ed69a6 in _PyEval_EvalCodeWithName ()
#105 0x0000563575ed7a11 in fast_function ()
#106 0x0000563575eddcc5 in call_function ()
#107 0x0000563575f02eb1 in _PyEval_EvalFrameDefault ()
#108 0x0000563575ed8529 in PyEval_EvalCodeEx ()
#109 0x0000563575ed92cc in PyEval_EvalCode ()
#110 0x0000563575f55af4 in run_mod ()
#111 0x0000563575f55b8d in PyRun_StringFlags ()
#112 0x0000563575effb32 in builtin_exec ()
#113 0x0000563575e4ff11 in _PyCFunction_FastCallDict ()
#114 0x0000563575eddbec in call_function ()
#115 0x0000563575f0219a in _PyEval_EvalFrameDefault ()
#116 0x0000563575ed8529 in PyEval_EvalCodeEx ()
#117 0x0000563575ed92cc in PyEval_EvalCode ()
#118 0x0000563575f55af4 in run_mod ()
#119 0x0000563575f55b8d in PyRun_StringFlags ()
#120 0x0000563575f55bef in PyRun_SimpleStringFlags ()
#121 0x0000563575f59a25 in Py_Main ()
#122 0x0000563575e2171e in main ()

```

**Comment by sh1ng** [comment]
Faced the same issue https://github.com/numpy/numpy/issues/7399

**Pull request closed without merging**
