### PR TITLE
Fix NOTE's found in CRAN

### PR DESCRIPTION
**Pull request by navdeep-G**
https://cran.r-project.org/web/checks/check_results_h2o4gpu.html

### CODE REVIEW

**Review by ledell — CHANGES_REQUESTED** [review]
@navdeep-G There's no need to Import the Matrix package, since it's not used in the h2o4gpu code.  It only seems to be used in the test suite:  https://github.com/h2oai/h2o4gpu/blob/0c59ce4a38ca1ed3214760a57ea062a80fc94f93/src/interface_r/tests/testthat/test_xgboost.R#L23

Therefore it should go in Suggests instead (see [here]() https://kbroman.org/pkg_primer/pages/depends.html).

**Comment by ledell** [comment]
@navdeep-G I pushed the changes I suggested above.  Can you re-submit to R-Hub to check that the LazyData edit is ok?

**Comment by navdeep-G** [comment]
@ledell Everything seems fine now:
```

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(devtools)
Loading required package: usethis
lib> library(rhub)

Attaching package: ârhubâ

The following object is masked from âpackage:devtoolsâ:

    check

> devtools::check_rhub("h2o4gpu/")
Building the package will delete...
  '/home/navdeep/h2o4gpu/src/interface_r/h2o4gpu/inst/doc'
Are you sure?

1: Yes
2: No

Selection: 1
â  checking for file â/home/navdeep/h2o4gpu/src/interface_r/h2o4gpu/DESCRIPTIONâ (505ms)
â  preparing âh2o4gpuâ:
â  checking DESCRIPTION meta-information ...
â  installing the package to build vignettes
â  creating vignettes (2.5s)
â  checking for LF line-endings in source and make files and shell scripts
â  checking for empty or unneeded directories
â  building âh2o4gpu_0.3.3.tar.gzâ
   
â  Uploading package
â  Preparing build, see status at
   https://builder.r-hub.io/status/h2o4gpu_0.3.3.tar.gz-2c56ec3ae12b468f9e76a44803ba667d
   https://builder.r-hub.io/status/h2o4gpu_0.3.3.tar.gz-872d4639e9394466b481141822f26744
   https://builder.r-hub.io/status/h2o4gpu_0.3.3.tar.gz-7dade76224864505946b6fb46ebb14f8
â  Build started
â  Creating new user
â  Downloading and unpacking package file
â  Querying package dependencies
â  Installing package dependencies
â  Running R CMD check
   setting _R_CHECK_FORCE_SUGGESTS_ to false
   setting R_COMPILE_AND_INSTALL_PACKAGES to never
   setting _R_CHECK_THINGS_IN_CHECK_DIR_ to false
   setting R_REMOTES_STANDALONE to true
   setting R_REMOTES_NO_ERRORS_FROM_WARNINGS to true
   setting _R_CHECK_FORCE_SUGGESTS_ to true
   setting _R_CHECK_CRAN_INCOMING_USE_ASPELL_ to true
   'getOption("repos")' replaces Bioconductor standard repositories, see
   replacement repositories:
       CRAN: https://cloud.r-project.org
   
   
   '?repositories' for details
â  using log directory 'C:/Users/USERMBGbAtjJzR/h2o4gpu.Rcheck'
â  using R Under development (unstable) (2021-04-15 r80175) (1.3s)
â  using platform: x86_64-w64-mingw32 (64-bit)
â  using session charset: ISO8859-1
â  using option '--as-cran'
â  checking for file 'h2o4gpu/DESCRIPTION' (644ms)
â  checking extension type ... Package
â  this is package 'h2o4gpu' version '0.3.3'
â  package encoding: UTF-8
N  checking CRAN incoming feasibility (1.3s)
   Maintainer: 'Navdeep Gill <navdeep@h2o.ai>'
   
   New maintainer:
     Navdeep Gill <navdeep@h2o.ai>
   Old maintainer(s):
     Yuan Tang <terrytangyuan@gmail.com>
â  checking package namespace information
â  checking package dependencies (1.3s)
â  checking if this is a source package
â  checking if there is a namespace
â  checking for executable files
â  checking for hidden files and directories (1.3s)
â  checking for portable file names
â  checking serialization versions
â  checking whether package 'h2o4gpu' can be installed
â  checking installed package size (640ms)
â  checking package directory
â  checking for future file timestamps
â  checking 'build' directory
â  checking DESCRIPTION meta-information (1.3s)
â  checking top-level files
â  checking for left-over files
â  checking index information
â  checking package subdirectories (640ms)
â  checking R files for non-ASCII characters
â  checking R files for syntax errors
â  checking whether the package can be loaded
â  checking whether the package can be loaded with stated dependencies (1.3s)
â  checking whether the package can be unloaded cleanly
â  checking whether the namespace can be loaded with stated dependencies
â  checking whether the namespace can be unloaded cleanly
â  checking loading without being on the library search path (641ms)
â  checking use of S3 registration
â  checking dependencies in R code
â  checking S3 generic/method consistency
â  checking replacement functions (1.3s)
â  checking foreign function calls
â  checking R code for possible problems
â  checking Rd files
â  checking Rd metadata (712ms)
â  checking Rd line widths
â  checking Rd cross-references
â  checking for missing documentation entries
â  checking for code/documentation mismatches (1.3s)
â  checking Rd \usage sections
â  checking Rd contents
â  checking for unstated dependencies in examples
â  checking installed files from 'inst/doc' (645ms)
â  checking files in 'vignettes'
â  checking examples
â  checking for unstated dependencies in 'tests'
â  checking tests (1.3s)
â  Running 'testthat.R'
â  checking for unstated dependencies in vignettes
â  checking package vignettes in 'inst/doc' (649ms)
â  checking re-building of vignette outputs
â  checking PDF version of manual (29.4s)
â  checking for non-standard things in the check directory
â  checking for detritus in the temp directory
   
â  Done with R CMD check
â  Cleaning up files and user
    

ââ h2o4gpu 0.3.3: NOTE

  Build ID:   h2o4gpu_0.3.3.tar.gz-2c56ec3ae12b468f9e76a44803ba667d
  Platform:   Windows Server 2008 R2 SP1, R-devel, 32/64 bit
  Submitted:  4m 2.3s ago
  Build time: 3m 59s

â¯ checking CRAN incoming feasibility ... NOTE
  Maintainer: 'Navdeep Gill <navdeep@h2o.ai>'
  
  New maintainer:
    Navdeep Gill <navdeep@h2o.ai>
  Old maintainer(s):
    Yuan Tang <terrytangyuan@gmail.com>

0 errors â | 0 warnings â | 1 note â

ââ h2o4gpu 0.3.3: IN-PROGRESS

  Build ID:   h2o4gpu_0.3.3.tar.gz-872d4639e9394466b481141822f26744
  Platform:   Ubuntu Linux 20.04.1 LTS, R-release, GCC
  Submitted:  4m 2.4s ago


ââ h2o4gpu 0.3.3: IN-PROGRESS

  Build ID:   h2o4gpu_0.3.3.tar.gz-7dade76224864505946b6fb46ebb14f8
  Platform:   Fedora Linux, R-devel, clang, gfortran
  Submitted:  4m 2.5s ago

> 

```

**Review by ledell — APPROVED** [review]
The R-Hub results look good!  Thanks, it's ready to merge.

**Pull request merged**
