### PR TITLE
Pass verbosity to c get info method

### PR DESCRIPTION
**Pull request by mdymczyk**
Some users are getting segfaults in this method (bitfusion) - hopefully more logs will help to pinpoint the problem.

### CODE REVIEW

**Comment by pseudotensor** [comment]
Sure, but that's not how it's used right now.  There are no other levels except 0 and 1, so I prefer to keep it as False and True for now so DAI and other uses do not break.

**Comment by mdymczyk** [comment]
@pseudotensor how about this, the API doesn't break (False is automatically handled as 0 and True prints everything) but also supports finer grained logging.

**Comment by pseudotensor** [comment]
Can you add check if verbose == False and set verbose = 0 too?

**Comment by mdymczyk** [comment]
@pseudotensor sure, done.

**Pull request merged**
